[package]
name = "ratelimit-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version="1.18.2", features = ["full"]}
governor = "0.10.0"
anyhow = "1.0.57"
futures = "0.3.21"